[build]
  command = "rm -f yarn.lock && npm install --legacy-peer-deps && NODE_OPTIONS=--openssl-legacy-provider npm run build"
  publish = ".next"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"
  YARN_ENABLED = "false"