[build]
  command = "npm install --no-package-lock --legacy-peer-deps && NODE_OPTIONS=--openssl-legacy-provider npm run build"
  publish = ".next"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "16.20.0"